using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace remitee.DTOs
{

    public class ResponseAPI
    {
        public bool success { get; set; }
        public string terms { get; set; }
        public string privacy { get; set; }
        public int timestamp { get; set; }
        public string source { get; set; }
        public Quotes quotes { get; set; }
    }

    public class Quotes
    {
        public decimal USDAED { get; set; }
        public decimal USDAFN { get; set; }
        public decimal USDALL { get; set; }
        public decimal USDAMD { get; set; }
        public decimal USDANG { get; set; }
        public decimal USDAOA { get; set; }
        public decimal USDARS { get; set; }
        public decimal USDAUD { get; set; }
        public decimal USDAWG { get; set; }
        public decimal USDAZN { get; set; }
        public decimal USDBAM { get; set; }
        public decimal USDBBD { get; set; }
        public decimal USDBDT { get; set; }
        public decimal USDBGN { get; set; }
        public decimal USDBHD { get; set; }
        public decimal USDBIF { get; set; }
        public decimal USDBMD { get; set; }
        public decimal USDBND { get; set; }
        public decimal USDBOB { get; set; }
        public decimal USDBRL { get; set; }
        public decimal USDBSD { get; set; }
        public decimal USDBTC { get; set; }
        public decimal USDBTN { get; set; }
        public decimal USDBWP { get; set; }
        public decimal USDBYN { get; set; }
        public decimal USDBYR { get; set; }
        public decimal USDBZD { get; set; }
        public decimal USDCAD { get; set; }
        public decimal USDCDF { get; set; }
        public decimal USDCHF { get; set; }
        public decimal USDCLF { get; set; }
        public decimal USDCLP { get; set; }
        public decimal USDCNY { get; set; }
        public decimal USDCOP { get; set; }
        public decimal USDCRC { get; set; }
        public decimal USDCUC { get; set; }
        public decimal USDCUP { get; set; }
        public decimal USDCVE { get; set; }
        public decimal USDCZK { get; set; }
        public decimal USDDJF { get; set; }
        public decimal USDDKK { get; set; }
        public decimal USDDOP { get; set; }
        public decimal USDDZD { get; set; }
        public decimal USDEGP { get; set; }
        public decimal USDERN { get; set; }
        public decimal USDETB { get; set; }
        public decimal USDEUR { get; set; }
        public decimal USDFJD { get; set; }
        public decimal USDFKP { get; set; }
        public decimal USDGBP { get; set; }
        public decimal USDGEL { get; set; }
        public decimal USDGGP { get; set; }
        public decimal USDGHS { get; set; }
        public decimal USDGIP { get; set; }
        public decimal USDGMD { get; set; }
        public decimal USDGNF { get; set; }
        public decimal USDGTQ { get; set; }
        public decimal USDGYD { get; set; }
        public decimal USDHKD { get; set; }
        public decimal USDHNL { get; set; }
        public decimal USDHRK { get; set; }
        public decimal USDHTG { get; set; }
        public decimal USDHUF { get; set; }
        public decimal USDIDR { get; set; }
        public decimal USDILS { get; set; }
        public decimal USDIMP { get; set; }
        public decimal USDINR { get; set; }
        public decimal USDIQD { get; set; }
        public decimal USDIRR { get; set; }
        public decimal USDISK { get; set; }
        public decimal USDJEP { get; set; }
        public decimal USDJMD { get; set; }
        public decimal USDJOD { get; set; }
        public decimal USDJPY { get; set; }
        public decimal USDKES { get; set; }
        public decimal USDKGS { get; set; }
        public decimal USDKHR { get; set; }
        public decimal USDKMF { get; set; }
        public decimal USDKPW { get; set; }
        public decimal USDKRW { get; set; }
        public decimal USDKWD { get; set; }
        public decimal USDKYD { get; set; }
        public decimal USDKZT { get; set; }
        public decimal USDLAK { get; set; }
        public decimal USDLBP { get; set; }
        public decimal USDLKR { get; set; }
        public decimal USDLRD { get; set; }
        public decimal USDLSL { get; set; }
        public decimal USDLTL { get; set; }
        public decimal USDLVL { get; set; }
        public decimal USDLYD { get; set; }
        public decimal USDMAD { get; set; }
        public decimal USDMDL { get; set; }
        public decimal USDMGA { get; set; }
        public decimal USDMKD { get; set; }
        public decimal USDMMK { get; set; }
        public decimal USDMNT { get; set; }
        public decimal USDMOP { get; set; }
        public decimal USDMRO { get; set; }
        public decimal USDMUR { get; set; }
        public decimal USDMVR { get; set; }
        public decimal USDMWK { get; set; }
        public decimal USDMXN { get; set; }
        public decimal USDMYR { get; set; }
        public decimal USDMZN { get; set; }
        public decimal USDNAD { get; set; }
        public decimal USDNGN { get; set; }
        public decimal USDNIO { get; set; }
        public decimal USDNOK { get; set; }
        public decimal USDNPR { get; set; }
        public decimal USDNZD { get; set; }
        public decimal USDOMR { get; set; }
        public decimal USDPAB { get; set; }
        public decimal USDPEN { get; set; }
        public decimal USDPGK { get; set; }
        public decimal USDPHP { get; set; }
        public decimal USDPKR { get; set; }
        public decimal USDPLN { get; set; }
        public decimal USDPYG { get; set; }
        public decimal USDQAR { get; set; }
        public decimal USDRON { get; set; }
        public decimal USDRSD { get; set; }
        public decimal USDRUB { get; set; }
        public decimal USDRWF { get; set; }
        public decimal USDSAR { get; set; }
        public decimal USDSBD { get; set; }
        public decimal USDSCR { get; set; }
        public decimal USDSDG { get; set; }
        public decimal USDSEK { get; set; }
        public decimal USDSGD { get; set; }
        public decimal USDSHP { get; set; }
        public decimal USDSLL { get; set; }
        public decimal USDSOS { get; set; }
        public decimal USDSRD { get; set; }
        public decimal USDSTD { get; set; }
        public decimal USDSVC { get; set; }
        public decimal USDSYP { get; set; }
        public decimal USDSZL { get; set; }
        public decimal USDTHB { get; set; }
        public decimal USDTJS { get; set; }
        public decimal USDTMT { get; set; }
        public decimal USDTND { get; set; }
        public decimal USDTOP { get; set; }
        public decimal USDTRY { get; set; }
        public decimal USDTTD { get; set; }
        public decimal USDTWD { get; set; }
        public decimal USDTZS { get; set; }
        public decimal USDUAH { get; set; }
        public decimal USDUGX { get; set; }
        public decimal USDUSD { get; set; }
        public decimal USDUYU { get; set; }
        public decimal USDUZS { get; set; }
        public decimal USDVEF { get; set; }
        public decimal USDVND { get; set; }
        public decimal USDVUV { get; set; }
        public decimal USDWST { get; set; }
        public decimal USDXAF { get; set; }
        public decimal USDXAG { get; set; }
        public decimal USDXAU { get; set; }
        public decimal USDXCD { get; set; }
        public decimal USDXDR { get; set; }
        public decimal USDXOF { get; set; }
        public decimal USDXPF { get; set; }
        public decimal USDYER { get; set; }
        public decimal USDZAR { get; set; }
        public decimal USDZMK { get; set; }
        public decimal USDZMW { get; set; }
        public decimal USDZWL { get; set; }
    }

}
